sources:
  - name: Order
    handler:
      openapi:
        source: http://localhost:8080/api-schema
    transforms:
      - rename:
          renames:
            - from:
                type: Query
                field: getProducts
              to:
                type: Query
                field: products
            - from:
                type: Query
                field: getProduct
              to:
                type: Query
                field: product
      - filterSchema:
          filters:
          - Query.!getProductVariants
      - typeMerging:
          queryFields:
            - queryFieldName: product
              keyField: id
transforms:
  - rename:
      renames:
        - from:
            type: (.*)DTO
          to:
            type: $1
          useRegExpForTypes: true
        - from:
            type: ProductDetail
          to:
            type: Product
  - typeMerging:
      queryFields:
        - queryFieldName: product
          keyField: id
